function injectTooltips(obj)
import iris.app.Info;

% Add CSS to obj.container head
containerScripts = utilities.scriptRead(...
  fullfile(Info.getResourcePath,'scripts','IrisStyles_2.css'), ...
  false, false, '''' ...
  );
containerText = sprintf(...
  'mystyle.innerHTML = `%s`;', ...
  containerScripts{:} ...
  );

% pause a little to let uielements finish updating
pause(0.2);
obj.window.executeJS( ...
  ['var mystyle;mystyle = document.createElement("style");', ...
  'document.head.appendChild(mystyle);'] ...
  );
% create a counter to prevent infinite attempts
i = 0;
while true
  try
    obj.window.executeJS(containerText);
  catch x
    %log this
    %fprintf(x.message);
    i = i+1;
    if i > 20, rethrow(x); end
    pause(0.2);
    continue
  end
  break;
end

% Add tooltips to different elements:
utilities.addTooltip(obj.FileReaderButton, ...
  'Create a new file reader method.', ...
  'left' ...
  );
utilities.addTooltip(obj.AnalysisPrefixPreviewString, ...
  'Preview of output analysis prefix.', ...
  'up' ...
  );
utilities.addTooltip(obj.BaselineRegionSelect, ...
  [ ...
    'Select region to calculate baseline. ', ...
    'Fit options utilize linear regression over Point(offset) range. ',  ...
    'Sym fits from Beginning and End while Asym only fits from Beginning.' ...
  ], ...
  'left' ...
  );
utilities.addTooltip(obj.SplitDevices, ...
  'Tick to aggregate indivual devices.', ...
  'left' ...
  );
utilities.addTooltip(obj.ZeroBaseline, ...
  'Set zeroing to occur during statistical calculations.', ...
  'up' ...
  );

end