function session = sessionReader(fileName)
%SESSIONREADER Read Iris Session Files
%   
try
  load(fileName,'-mat','session');
  if ~all(contains(fieldnames(session),{'Meta','Data','Notes','Files'}))
    throw( ...
      MException( ...
        'SessionReader:ImportStruct', ...
        'File does not contain correct fields' ...
        ) ...
      );
  end
catch e
  er = MException( ...
    'SessionReader:ImportStruct', ...
    'Session reader failed with message: "%s".', e.message ...
    );
  throw(er);
end

end

