function [avgs] = averagedDatums(Data,groupBy,baselineType,lowpassCutoff)
%% averagedDatums
%{
DEFAULTS
groupBy:='lightAmplitude'
baselineType:='Sym'
lowpassCutoff:=30
%}

%% Begin Analysis
% aggregate data based on groups
avgs = Data.Filter( ...
    'type','lowpass', ...
    'freq',lowpassCutoff ...
  ).Aggregate( ...
    'groupby', groupBy, ...
    'baselineRegion', baselineType, ...
    'statistic', 'mean' ...
  );
% plot the aggregates in a new window.
plot(avgs, 'legend', true);
% end of analysis
end