function [avgs] = averagedEpochs(Data,groupBy,baselineType)
%% averagedEpochs
%{
DEFAULTS
groupBy:='lightAmplitude'
baselineType:='Sym'
%}

%% Begin Analysis
% aggregate data based on groups
avgs = Data.Filter( ...
    'type','lowpass', ...
    'freq',30 ...
  ).Aggregate( ...
    'groupby', groupBy, ...
    'baselineRegion', baselineType, ...
    'statistic', {'mean'} ...
  );
% plot the aggregates in a new window.
plot(avgs, 'legend', true, 'position', [100,100,800,450]);
% end of analysis
end