function par = pointPar(color,target)
  arguments
    color (1,3) double
    target (1,1) string = ""
  end
  pcol = brighten(color,-0.5);
  par = { ...
    'Color', pcol, ...
    'Marker','o', ...
    'MarkerFaceColor',pcol,...
    'MarkerSize', 7.5, ...
    'LineStyle', 'none' ...
    };
  if target ~= ""
    par(end+(1:2)) = {'Tag', target+"_P"};
  end
end

