function appInfo = info()
import matlab.internal.apputil.AppUtil;

% find IrisApp install location
infos = AppUtil.getAllAppsInDefaultLocation;
appIndex = AppUtil.findAppIDs( ...
  {infos.id}, ...
  [IrisDVA.APP_NAME,IrisDVA.APP_ID], ...
  false ...
  );
appInfo = infos(appIndex);
end