function p = centerFigPos(w, h)
s = get(0, 'ScreenSize');
if any([w<=1 && w>0,h<=1 && h>0])
  if ~all([w<=1 && w>0,h<=1 && h>0])
    error('If w & h are normalized, must be (0,1].');
  end
  w = w*s(3);
  h = h*s(4);
end

p = ...
  [...
  (s(3) - w) / 2, ...
  (s(4) - h) / 2, ...
  w, ...
  h...
  ];
end