function tableDat = collapseUnique(d,columnAnchor)
keyNames = unique(d(:,columnAnchor),'stable');
others = ~ismember(1:size(d,2), columnAnchor);
keyData = cellfun( ...
  @(x)d(ismember(d(:,columnAnchor),x),others), ...
  keyNames, ...
  'UniformOutput', false ...
  );
if length(keyNames) == size(d,columnAnchor)
  tableDat = d;
else
  tableDat = [ ...
    keyNames(:), ...
    keyData(:) ...
    ];
end
% set all values column to strings
tableDat(:,2) = arrayfun(@unknownCell2Str,tableDat(:,2),'unif',0);
end

