function fig = createIrisUiFigure(name,width,height,visible,figureParams)
%CREATEIRISFIGURE Creates a figure with iris theming

arguments
  name string = "Figure"
  width (1,1) double {mustBeNonnegative} = 1000
  height (1,1) double {mustBeNonnegative} = 650
  visible matlab.lang.OnOffSwitchState = 'off'
  figureParams.?matlab.ui.Figure
end

import utilities.centerFigPos;

% defaults
params = [ ...
  {'autoresizechildren';'off'}, ...
  {'color';[1,1,1]}, ...
  {'defaultanimatedlineinterruptible';'off'}, ...
  {'defaultareainterruptible';'off'}, ...
  {'defaultarrowshapeinterruptible';'off'}, ...
  {'defaultaxesbox';'off'}, ...
  {'defaultaxescolor';[1,1,1,0]}, ...
  {'defaultaxesfontname';'Times New Roman'}, ...
  {'defaultaxesfontsize';16}, ...
  {'defaultaxesinterruptible';'off'}, ...
  {'defaultaxestoolbarinterruptible';'off'}, ...
  {'defaultaxesxlimmode';'manual'}, ...
  {'defaultaxesylimmode';'manual'}, ...
  {'defaultbarinterruptible';'off'}, ...
  {'defaultbinscatterinterruptible';'off'}, ...
  {'defaultcategoricalhistograminterruptible';'off'}, ...
  {'defaultcolorbarinterruptible';'off'}, ...
  {'defaultcontourinterruptible';'off'}, ...
  {'defaultdoubleendarrowshapeinterruptible';'off'}, ...
  {'defaultellipseshapeinterruptible';'off'}, ...
  {'defaulterrorbarinterruptible';'off'}, ...
  {'defaultfigureinterruptible';'off'}, ...
  {'defaultfunctioncontourinterruptible';'off'}, ...
  {'defaultfunctionlineinterruptible';'off'}, ...
  {'defaultfunctionsurfaceinterruptible';'off'}, ...
  {'defaultgeoaxesinterruptible';'off'}, ...
  {'defaultgraphplotinterruptible';'off'}, ...
  {'defaulthggroupinterruptible';'off'}, ...
  {'defaulthgjavacomponentbackgroundcolor';[1,1,1]}, ...
  {'defaulthgjavacomponentinterruptible';'off'}, ...
  {'defaulthgtransforminterruptible';'off'}, ...
  {'defaulthistogram2interruptible';'off'}, ...
  {'defaulthistograminterruptible';'off'}, ...
  {'defaultimageinterruptible';'off'}, ...
  {'defaultimplicitfunctionlineinterruptible';'off'}, ...
  {'defaultimplicitfunctionsurfaceinterruptible';'off'}, ...
  {'defaultlegendinterruptible';'off'}, ...
  {'defaultlightinterruptible';'off'}, ...
  {'defaultlineinterruptible';'off'}, ...
  {'defaultlineshapeinterruptible';'off'}, ...
  {'defaultparameterizedfunctionlineinterruptible';'off'}, ...
  {'defaultparameterizedfunctionsurfaceinterruptible';'off'}, ...
  {'defaultpatchinterruptible';'off'}, ...
  {'defaultpolaraxesinterruptible';'off'}, ...
  {'defaultquiverinterruptible';'off'}, ...
  {'defaultrectangleinterruptible';'off'}, ...
  {'defaultrectangleshapeinterruptible';'off'}, ...
  {'defaultscatterinterruptible';'off'}, ...
  {'defaultstairinterruptible';'off'}, ...
  {'defaultsteminterruptible';'off'}, ...
  {'defaultsurfaceinterruptible';'off'}, ...
  {'defaulttextarrowshapeinterruptible';'off'}, ...
  {'defaulttextbackgroundcolor';[1,1,1,0]}, ...
  {'defaulttextboxshapeinterruptible';'off'}, ...
  {'defaulttextfontname';'Times New Roman'}, ...
  {'defaulttextfontsize';18}, ...
  {'defaulttextinterruptible';'off'}, ...
  {'defaultuibuttongroupautoresizechildren';'off'}, ...
  {'defaultuibuttongroupbordertype';'line'}, ...
  {'defaultuibuttongroupfontname';'Times New Roman'}, ...
  {'defaultuibuttongroupfontsize';16}, ...
  {'defaultuibuttongroupfontunits';'pixels'}, ...
  {'defaultuibuttongroupinterruptible';'off'}, ...
  {'defaultuibuttongroupposition';[20,20,260,210]}, ...
  {'defaultuibuttongroupunits';'pixels'}, ...
  {'defaultuicontainerbackgroundcolor';[1,1,1]}, ...
  {'defaultuicontainerinterruptible';'off'}, ...
  {'defaultuicontextmenuinterruptible';'off'}, ...
  {'defaultuicontrolbackgroundcolor';[1,1,1,0]}, ...
  {'defaultuicontrolfontname';'Times New Roman'}, ...
  {'defaultuicontrolinterruptible';'off'}, ...
  {'defaultuiflowcontainerinterruptible';'off'}, ...
  {'defaultuigridcontainerbackgroundcolor';[1,1,1]}, ...
  {'defaultuigridcontainerinterruptible';'off'}, ...
  {'defaultuigridcontainerclipping'; 'off' }, ...
  {'defaultuimenuinterruptible';'off'}, ...
  {'defaultuipanelautoresizechildren';'off'}, ...
  {'defaultuipanelbackgroundcolor';[1,1,1,0]}, ...
  {'defaultuipanelbordertype';'line'}, ...
  {'defaultUipanelFontName';'Times New Roman'}, ...
  {'defaultuipanelfontsize';16}, ...
  {'defaultuipanelfontunits';'pixels'}, ...
  {'defaultuipanelinterruptible';'off'}, ...
  {'defaultuipanelposition';[20,20,260,221]}, ...
  {'defaultuipanelunits';'pixels'}, ...
  {'defaultuipushtoolinterruptible';'off'}, ...
  {'defaultuisplittoolinterruptible';'off'}, ...
  {'defaultuitabautoresizechildren';'off'}, ...
  {'defaultuitabbackgroundcolor';[1,1,1]}, ...
  {'defaultuitabgroupautoresizechildren';'off'}, ...
  {'defaultuitabgroupinterruptible';'off'}, ...
  {'defaultuitabgroupposition';[20,20,250,210]}, ...
  {'defaultuitabgroupunits';'pixels'}, ...
  {'defaultuitabinterruptible';'off'}, ...
  {'defaultuitablebackgroundcolor';[1,1,1]}, ...
  {'defaultuitablebusyaction';'cancel'}, ...
  {'defaultUitableFontName';'Times New Roman'}, ...
  {'defaultuitablefontsize';12}, ...
  {'defaultuitablefontunits';'pixels'}, ...
  {'defaultuitableinterruptible';'off'}, ...
  {'defaultuitabunits';'pixels'}, ...
  {'defaultuitogglesplittoolinterruptible';'off'}, ...
  {'defaultuitoggletoolinterruptible';'off'}, ...
  {'defaultuitoolbarinterruptible';'off'}, ...
  {'handlevisibility';'off'}, ...
  {'menubar';'none'}, ...
  {'resize';'on'}, ...
  {'toolbar';'none'}, ...
  {'visible';'off'} ...
  ];

fig = uifigure('name',name,'position',centerFigPos(width,height),'Visible','off');

for p = 1:size(params,2)
  try 
    set(fig,params{1,p},params{2,p});
  catch
    fprintf('%s skipped.\n',params{1,p});
  end
end

fig.Visible = visible;
end

